/** public/stikers — regenerate with: node scripts/generate-asset-stickers.mjs */
export const ASSET_STICKER_SRCS = [
  "/stikers/baking.png",
  "/stikers/balloons.png",
  "/stikers/baseball.png",
  "/stikers/basketball (1).png",
  "/stikers/basketball-hoop.png",
  "/stikers/basketball.png",
  "/stikers/bear.png",
  "/stikers/bee.png",
  "/stikers/bell-pepper.png",
  "/stikers/birthday-cake (1).png",
  "/stikers/birthday-cake (2).png",
  "/stikers/birthday-cake (3).png",
  "/stikers/birthday-cake.png",
  "/stikers/birthday.png",
  "/stikers/blowfish.png",
  "/stikers/board-game.png",
  "/stikers/boxing.png",
  "/stikers/breakfast.png",
  "/stikers/burger.png",
  "/stikers/butterfly.png",
  "/stikers/cake.png",
  "/stikers/carrot.png",
  "/stikers/cat.png",
  "/stikers/chameleon.png",
  "/stikers/cheetah.png",
  "/stikers/chicken.png",
  "/stikers/chili-pepper.png",
  "/stikers/cookies.png",
  "/stikers/cupcake.png",
  "/stikers/dancing.png",
  "/stikers/dolphin.png",
  "/stikers/donut.png",
  "/stikers/embroidery.png",
  "/stikers/farming.png",
  "/stikers/fishing.png",
  "/stikers/football.png",
  "/stikers/french-fries.png",
  "/stikers/gaming.png",
  "/stikers/golf.png",
  "/stikers/gorilla.png",
  "/stikers/guitar.png",
  "/stikers/hammerhead.png",
  "/stikers/hamster.png",
  "/stikers/hot-dog.png",
  "/stikers/ice-cream.png",
  "/stikers/japanese-food.png",
  "/stikers/kebab.png",
  "/stikers/mouse.png",
  "/stikers/noodles.png",
  "/stikers/nymph.png",
  "/stikers/onigiri.png",
  "/stikers/ostrich.png",
  "/stikers/painting.png",
  "/stikers/pancake.png",
  "/stikers/panda.png",
  "/stikers/penguin.png",
  "/stikers/pictures.png",
  "/stikers/ping-pong.png",
  "/stikers/pizza.png",
  "/stikers/pottery.png",
  "/stikers/rabbit.png",
  "/stikers/radish.png",
  "/stikers/reading.png",
  "/stikers/reindeer.png",
  "/stikers/roller-skates.png",
  "/stikers/running (1).png",
  "/stikers/running.png",
  "/stikers/sandwich (1).png",
  "/stikers/sandwich.png",
  "/stikers/santa-claus (1).png",
  "/stikers/santa-claus (2).png",
  "/stikers/santa-claus (3).png",
  "/stikers/santa-claus.png",
  "/stikers/sea-turtle.png",
  "/stikers/skateboard.png",
  "/stikers/snail.png",
  "/stikers/spaghetti.png",
  "/stikers/stamp.png",
  "/stikers/strawberry.png",
  "/stikers/sushi.png",
  "/stikers/swimmer.png",
  "/stikers/taco.png",
  "/stikers/telescope.png",
  "/stikers/tennis.png",
  "/stikers/tomatoes.png",
  "/stikers/volleyball.png",
  "/stikers/waffle.png",
  "/stikers/walrus.png",
  "/stikers/whistle.png"
] as const;

export const PACK_STICKER_CATEGORY = {
  id: 'pack',
  label: '일러스트',
  icon: '🎨',
  items: ASSET_STICKER_SRCS.map((src) => ({ src })),
} as const;

export function isAssetStickerSrc(value: string): boolean {
  return value.startsWith('/stikers/');
}

/** public/stikers 파일명에 공백·괄호가 있어도 브라우저에서 로드되게 인코딩 */
export function toAssetStickerUrl(src: string): string {
  if (!isAssetStickerSrc(src)) return src;
  const parts = src.split('/').filter(Boolean);
  return `/${parts.map(encodeURIComponent).join('/')}`;
}
